//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TxClient.TxRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TxRef.ITxService")]
    public interface ITxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITxService/TxOperation", ReplyAction="http://tempuri.org/ITxService/TxOperationResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        bool TxOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITxService/TxOperation", ReplyAction="http://tempuri.org/ITxService/TxOperationResponse")]
        System.Threading.Tasks.Task<bool> TxOperationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITxServiceChannel : TxClient.TxRef.ITxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TxServiceClient : System.ServiceModel.ClientBase<TxClient.TxRef.ITxService>, TxClient.TxRef.ITxService {
        
        public TxServiceClient() {
        }
        
        public TxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TxOperation() {
            return base.Channel.TxOperation();
        }
        
        public System.Threading.Tasks.Task<bool> TxOperationAsync() {
            return base.Channel.TxOperationAsync();
        }
    }
}
